FROM registry.access.redhat.com/ubi9/python-311@sha256:fae422b4e7dbc2e551919fb87b6004c06b731179be2ed2904427531a2d1ef3a2

USER 0
COPY src .
RUN chown -R 1001:0 ./
USER 1001

RUN pip install -r requirements.txt

ENTRYPOINT python app.py