apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-api
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/Carlos-ZRM/openshift-app.git
    targetRevision: HEAD
    path: jupyter/tekton
  destination:
    server: https://kubernetes.default.svc
    namespace: notapipe