apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp-api-dev
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/sjose165/openshift-app-tam.git
    targetRevision: HEAD
    path: jupyter/ocp-api/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: sergio-project-prueba
