apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pipeline-ci-api-
spec:
  pipelineRef:
    name: pipeline-ci-api
  workspaces:
  - name: workspace-git
    persistentVolumeClaim:
      claimName: pvc-git-api
  params:
  - name: repo-url
    value: https://github.com/sjose165/openshift-app-tam.git
  - name: img-registry
    value: default-route-openshift-image-registry.apps.ocp.dev.cfeteit.mx/sergio-project-prueba/api:latest
  - name: img-context
    value: python/openapi
  - name: img-dockerfile
    value: Containerfile
